version: 1
builder:
  configs:
    - documentation_targets:
        - WasmKit
        - WasmKitWASI
        - WasmParser
        - WASI
        - WIT
        - WITExtractor
        - WITOverlayGenerator
        - WITTool
